# See README.md for extra documentation on the specifics of an element.
---
mode: "development" # can either be "development" or "production"
debug: false # enable debug messages
image_directory_url: "https://uwindsorcss.github.io/files/dir/images/buildings"

year_roles:
  1: ""
  2: ""
  3: ""
  4: ""
  4+: ""
  Masters: ""

# featurization - if you want to disable a feature, set it to false
features:
  art: true
  edit: true
  equation: true
  free: true
  help: true
  jail: true
  link: true
  linkAdmin: true
  ping: true
  prompt: true
  purge: true
  say: true
  whereis: true
  year: true
  google: true
