# See README.md for extra documentation on the specifics of an element.
---
seed: false # Set to false to disable seeding of the database
debug: false # used for debug messages
image_directory_url: "https://uwindsorcss.github.io/files/dir/images/buildings"

# Discord Credentials
discord_api_version: "10"
discord_api_token: ""
discord_client_id: ""
discord_guild_id: ""

# GSCE Credentials
google_search_key: ""
google_search_id: ""

year_roles:
  1: ""
  2: ""
  3: ""
  4: ""
  4+: ""
  Masters: ""

# featurization - if you want to disable a feature, set it to false
features:
  art: true
  edit: true
  equation: true
  free: true
  help: true
  jail: true
  link: true
  linkAdmin: true
  ping: true
  prompt: true
  purge: true
  say: true
  whereis: true
  year: true
  google: true
  course: true
